#represents the task such as classification, segmentation etc
Task:
  value: 0
  epochs: 1

#location of the test images
TestInput:
  dataset: required
  batch_size: 4
  testdir:
    annotations: []
    images: sample/sampleImages/smallCF
    testNames: []

taskParams: taskParams.yml

#official keras model or link to a model compiled in keras
Model:
  kerasmodel: vgg16
  customObjects:
    module: []
    class: []
    functions: []

#one of the keras layer names
SplitLayer:
  split: block1_pool 

#transmission parameters
Transmission:
  rowsperpacket: 8 #packetization parameter
  quantization:
    numberOfBits: 8
    include: False
  channel: #type of channel
    RandomLossChannel:
      lossProbability: 0
      include: False
    GilbertChannel: #change to include if no channel is selected
      lossProbability: 0.3
      burstLength: 5
      include: False
  concealment: #type of error concealment
    Linear:
      include: False
    nearestNeighbours:
      include: False

OutputDir:
  simDataDir: '../simData/0Loss'
