#represents the task such as classification, segmentation etc
Task:
  value: 1
  epochs: 1

#location of the test images
TestInput:
  dataset: voc2007
  batch_size: 8
  testdir: [C:\Users\hunnibha\Desktop\datasets\VOCdevkit\VOC2007\JPEGImages, C:\Users\hunnibha\Desktop\datasets\VOCdevkit\VOC2007\Annotations, C:\Users\hunnibha\Desktop\datasets\VOCdevkit\VOC2007\ImageSets\Main\test.txt]

PreProcess: preprocess.yml

#official keras model or link to a model compiled in keras
Model:
  kerasmodel: C:\Users\hunnibha\Desktop\ssd_keras\models\ssdModel.h5
  customObjects:
    module: [keras_layers.keras_layer_AnchorBoxes, keras_layers.keras_layer_DecodeDetections, keras_layers.keras_layer_DecodeDetectionsFast, keras_layers.keras_layer_L2Normalization]
    class: [AnchorBoxes, DecodeDetections, DecodeDetectionsFast, L2Normalization]

#one of the keras layer names
SplitLayer:
  split: fc6

#transmission parameters
Transmission:
  rowsperpacket: 8 #packetization parameter
  quantization:
    numberOfBits: 8
    include: True
  channel: #type of channel
    RandomLossChannel:
      lossProbability: 1
      include: False
    GilbertChannel:
      lossProbability: 0.01
      burstLength: 2
      include: True
  concealment: #type of error concealment
    Linear:
      include: False
    nearestNeighbours:
      include: False

OutputDir:
  simDataDir: '..\simData\10Loss_2bl'
