#represents the task such as classification, segmentation etc
Task:
  value: 1
  epochs: 1

#location of the test images
TestInput:
  dataset: voc2007
  batch_size: 4
  testdir:
    # annotations: []
    # images: C:/Users/Harsha/Desktop/largeTest

    # annotations: ["C:/Users/Harsha/Desktop/datasets/VOCdevkit/VOC2007/Annotations"]
    # images: ["C:/Users/Harsha/Desktop/datasets/VOCdevkit/VOC2007/JPEGImages"]
    # testNames: ["C:/Users/Harsha/Desktop/datasets/VOCdevkit/VOC2007/ImageSets/Main/test.txt"]

    annotations: ["C:/Users/Harsha/Desktop/miniVOC/Annotations"]
    images: ["C:/Users/Harsha/Desktop/miniVOC/JPEGImages"]
    testNames: ["C:/Users/Harsha/Desktop/miniVOC/test.txt"]

taskParams: taskParams.yml

#official keras model or link to a model compiled in keras
Model:
  kerasmodel: "C:/Users/Harsha/Desktop/ssd_keras/models/ssdModel.h5"
  # kerasmodel: vgg16
  customObjects:
    module: [keras_layers.keras_layer_AnchorBoxes, keras_layers.keras_layer_DecodeDetections, keras_layers.keras_layer_L2Normalization]
    class: [AnchorBoxes, DecodeDetections, L2Normalization]

#one of the keras layer names
SplitLayer:
  split: fc6

#transmission parameters
Transmission:
  rowsperpacket: 8 #packetization parameter
  quantization:
    numberOfBits: 8
    include: False
  channel: #type of channel
    RandomLossChannel:
      lossProbability: 0
      include: False
    GilbertChannel: #change to include if no channel is selected
      lossProbability: 0.5
      burstLength: 5
      include: False
  concealment: #type of error concealment
    Linear:
      include: False
    nearestNeighbours:
      include: False

OutputDir:
  simDataDir: '../simData/10Loss_2bl'
